baseURL = "https://example.org/"
languageCode = "pt-br"
title = "My New Hugo Site"
theme = "simplog"
author = "Tet"
description = "Jovem de 24 anos tentando ser jornalista."

[params]
    colorTheme = "default"