baseURL = "https://www.tetizeraz.online"
languageCode = "pt-br"
title = "Tet's Blog"
themesDir = "themes"
theme = "hyde"
author = "Tet"
description = "Jovem de 24 anos tentando ser jornalista."
sectionPagesMenu = "main"

[[menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts/"
weight     = 110

[params]
    themeColor = "theme-base-08"