baseURL = "https://ecstatic-golick-b291f7.netlify.app"
languageCode = "pt-br"
title = "Tet's Blog"
themesDir = "themes"
theme = "simplog"
author = "Tet"
description = "Jovem de 24 anos tentando ser jornalista."
sectionPagesMenu = "main"

[[menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts/"
weight     = 110

[params]
    colorTheme = "default"